<?php
if (isset($_GET["continents"])) {
    echo json_encode(array(
        array("id" => 1, "name" => "Europe"),
        array("id" => 2, "name" => "Asia"),
        array("id" => 3, "name" => "North America"),
        array("id" => 4, "name" => "South America"),
        array("id" => 5, "name" => "Australia and Oceania"),
        array("id" => 6, "name" => "Africa")
    ));
} else {
    echo json_encode(array(
        array("id" => 1, "name" => "Albania"),
        array("id" => 1, "name" => "Andorra"),
        array("id" => 1, "name" => "Austria"),
        array("id" => 1, "name" => "Belarus"),
        array("id" => 1, "name" => "Belgium"),
        array("id" => 1, "name" => "Bosnia and Herzegovina"),
        array("id" => 1, "name" => "Bulgaria"),
        array("id" => 1, "name" => "Croatia"),
        array("id" => 1, "name" => "Cyprus"),
        array("id" => 1, "name" => "Czech Republic"),
        array("id" => 1, "name" => "Denmark"),
        array("id" => 1, "name" => "East Germany"),
        array("id" => 1, "name" => "Estonia"),
        array("id" => 1, "name" => "Faroe Islands"),
        array("id" => 1, "name" => "Finland"),
        array("id" => 1, "name" => "France"),
        array("id" => 1, "name" => "Germany"),
        array("id" => 1, "name" => "Gibraltar"),
        array("id" => 1, "name" => "Greece"),
        array("id" => 1, "name" => "Guernsey"),
        array("id" => 1, "name" => "Hungary"),
        array("id" => 1, "name" => "Iceland"),
        array("id" => 1, "name" => "Ireland"),
        array("id" => 1, "name" => "Isle of Man"),
        array("id" => 1, "name" => "Italy"),
        array("id" => 1, "name" => "Jersey"),
        array("id" => 1, "name" => "Latvia"),
        array("id" => 1, "name" => "Liechtenstein"),
        array("id" => 1, "name" => "Lithuania"),
        array("id" => 1, "name" => "Luxembourg"),
        array("id" => 1, "name" => "Macedonia"),
        array("id" => 1, "name" => "Malta"),
        array("id" => 1, "name" => "Metropolitan France"),
        array("id" => 1, "name" => "Moldova"),
        array("id" => 1, "name" => "Monaco"),
        array("id" => 1, "name" => "Montenegro"),
        array("id" => 1, "name" => "Netherlands"),
        array("id" => 1, "name" => "Norway"),
        array("id" => 1, "name" => "Poland"),
        array("id" => 1, "name" => "Portugal"),
        array("id" => 1, "name" => "Romania"),
        array("id" => 1, "name" => "Russia"),
        array("id" => 1, "name" => "San Marino"),
        array("id" => 1, "name" => "Serbia"),
        array("id" => 1, "name" => "Serbia and Montenegro"),
        array("id" => 1, "name" => "Slovakia"),
        array("id" => 1, "name" => "Slovenia"),
        array("id" => 1, "name" => "Spain"),
        array("id" => 1, "name" => "Svalbard and Jan Mayen"),
        array("id" => 1, "name" => "Sweden"),
        array("id" => 1, "name" => "Switzerland"),
        array("id" => 1, "name" => "Ukraine"),
        array("id" => 1, "name" => "Union of Soviet Socialist Republics"),
        array("id" => 1, "name" => "United Kingdom"),
        array("id" => 1, "name" => "Vatican City"),
        array("id" => 1, "name" => "Åland Islands"),
        array("id" => 2, "name" => "Afghanistan"),
        array("id" => 2, "name" => "Armenia"),
        array("id" => 2, "name" => "Azerbaijan"),
        array("id" => 2, "name" => "Bahrain"),
        array("id" => 2, "name" => "Bangladesh"),
        array("id" => 2, "name" => "Bhutan"),
        array("id" => 2, "name" => "Brunei"),
        array("id" => 2, "name" => "Cambodia"),
        array("id" => 2, "name" => "China"),
        array("id" => 2, "name" => "Cyprus"),
        array("id" => 2, "name" => "Georgia"),
        array("id" => 2, "name" => "Hong Kong SAR China"),
        array("id" => 2, "name" => "India"),
        array("id" => 2, "name" => "Indonesia"),
        array("id" => 2, "name" => "Iran"),
        array("id" => 2, "name" => "Iraq"),
        array("id" => 2, "name" => "Israel"),
        array("id" => 2, "name" => "Japan"),
        array("id" => 2, "name" => "Jordan"),
        array("id" => 2, "name" => "Kazakhstan"),
        array("id" => 2, "name" => "Kuwait"),
        array("id" => 2, "name" => "Kyrgyzstan"),
        array("id" => 2, "name" => "Laos"),
        array("id" => 2, "name" => "Lebanon"),
        array("id" => 2, "name" => "Macau SAR China"),
        array("id" => 2, "name" => "Malaysia"),
        array("id" => 2, "name" => "Maldives"),
        array("id" => 2, "name" => "Mongolia"),
        array("id" => 2, "name" => "Myanmar [Burma]"),
        array("id" => 2, "name" => "Nepal"),
        array("id" => 2, "name" => "Neutral Zone"),
        array("id" => 2, "name" => "North Korea"),
        array("id" => 2, "name" => "Oman"),
        array("id" => 2, "name" => "Pakistan"),
        array("id" => 2, "name" => "Palestinian Territories"),
        array("id" => 2, "name" => "People's Democratic Republic of Yemen"),
        array("id" => 2, "name" => "Philippines"),
        array("id" => 2, "name" => "Qatar"),
        array("id" => 2, "name" => "Saudi Arabia"),
        array("id" => 2, "name" => "Singapore"),
        array("id" => 2, "name" => "South Korea"),
        array("id" => 2, "name" => "Sri Lanka"),
        array("id" => 2, "name" => "Syria"),
        array("id" => 2, "name" => "Taiwan"),
        array("id" => 2, "name" => "Tajikistan"),
        array("id" => 2, "name" => "Thailand"),
        array("id" => 2, "name" => "Timor-Leste"),
        array("id" => 2, "name" => "Turkey"),
        array("id" => 2, "name" => "Turkmenistan"),
        array("id" => 2, "name" => "United Arab Emirates"),
        array("id" => 2, "name" => "Uzbekistan"),
        array("id" => 2, "name" => "Vietnam"),
        array("id" => 2, "name" => "Yemen"),
        array("id" => 3, "name" => "Antigua & Barbuda"),
        array("id" => 3, "name" => "Bahamas"),
        array("id" => 3, "name" => "Barbados"),
        array("id" => 3, "name" => "Belize"),
        array("id" => 3, "name" => "Canada"),
        array("id" => 3, "name" => "Costa Rica"),
        array("id" => 3, "name" => "Cuba"),
        array("id" => 3, "name" => "Dominica"),
        array("id" => 3, "name" => "Dominican Republic"),
        array("id" => 3, "name" => "El Salvador"),
        array("id" => 3, "name" => "Grenada"),
        array("id" => 3, "name" => "Guatemala"),
        array("id" => 3, "name" => "Haiti"),
        array("id" => 3, "name" => "Honduras"),
        array("id" => 3, "name" => "Jamaica"),
        array("id" => 3, "name" => "Mexico"),
        array("id" => 3, "name" => "Nicaragua"),
        array("id" => 3, "name" => "Panama"),
        array("id" => 3, "name" => "St. Kitts & Nevis"),
        array("id" => 3, "name" => "St. Lucia"),
        array("id" => 3, "name" => "St. Vincent & The Grenadines"),
        array("id" => 3, "name" => "Trinidad & Tobago"),
        array("id" => 3, "name" => "United States of America"),
        array("id" => 4, "name" => "Argentina"),
        array("id" => 4, "name" => "Bolivia"),
        array("id" => 4, "name" => "Brazil"),
        array("id" => 4, "name" => "Chile"),
        array("id" => 4, "name" => "Colombia"),
        array("id" => 4, "name" => "Ecuador"),
        array("id" => 4, "name" => "Guyana"),
        array("id" => 4, "name" => "Paraguay"),
        array("id" => 4, "name" => "Peru"),
        array("id" => 4, "name" => "Suriname"),
        array("id" => 4, "name" => "Uruguay"),
        array("id" => 4, "name" => "Venezuela"),
        array("id" => 5, "name" => "Australia"),
        array("id" => 5, "name" => "Fiji"),
        array("id" => 5, "name" => "Kiribati"),
        array("id" => 5, "name" => "Marshall Islands"),
        array("id" => 5, "name" => "Micronesia"),
        array("id" => 5, "name" => "Samoa"),
        array("id" => 5, "name" => "Solomon Islands"),
        array("id" => 5, "name" => "Nauru"),
        array("id" => 5, "name" => "New Zealand"),
        array("id" => 5, "name" => "Palau"),
        array("id" => 5, "name" => "Papua New Guinea"),
        array("id" => 5, "name" => "Tonga"),
        array("id" => 5, "name" => "Tuvalu"),
        array("id" => 5, "name" => "Vanuatu"),
        array("id" => 6, "name" => "Algeria"),
        array("id" => 6, "name" => "Angola"),
        array("id" => 6, "name" => "Benin"),
        array("id" => 6, "name" => "Botswana"),
        array("id" => 6, "name" => "Burkina Faso"),
        array("id" => 6, "name" => "Burundi"),
        array("id" => 6, "name" => "Cameroon"),
        array("id" => 6, "name" => "Cape Verde"),
        array("id" => 6, "name" => "Central African Republic"),
        array("id" => 6, "name" => "Chad"),
        array("id" => 6, "name" => "Comoros"),
        array("id" => 6, "name" => "Congo - Brazzaville"),
        array("id" => 6, "name" => "Congo - Kinshasa"),
        array("id" => 6, "name" => "Côte d’Ivoire"),
        array("id" => 6, "name" => "Djibouti"),
        array("id" => 6, "name" => "Egypt"),
        array("id" => 6, "name" => "Equatorial Guinea"),
        array("id" => 6, "name" => "Eritrea"),
        array("id" => 6, "name" => "Ethiopia"),
        array("id" => 6, "name" => "Gabon"),
        array("id" => 6, "name" => "Gambia"),
        array("id" => 6, "name" => "Ghana"),
        array("id" => 6, "name" => "Guinea"),
        array("id" => 6, "name" => "Guinea-Bissau"),
        array("id" => 6, "name" => "Kenya"),
        array("id" => 6, "name" => "Lesotho"),
        array("id" => 6, "name" => "Liberia"),
        array("id" => 6, "name" => "Libya"),
        array("id" => 6, "name" => "Madagascar"),
        array("id" => 6, "name" => "Malawi"),
        array("id" => 6, "name" => "Mali"),
        array("id" => 6, "name" => "Mauritania"),
        array("id" => 6, "name" => "Mauritius"),
        array("id" => 6, "name" => "Mayotte"),
        array("id" => 6, "name" => "Morocco"),
        array("id" => 6, "name" => "Mozambique"),
        array("id" => 6, "name" => "Namibia"),
        array("id" => 6, "name" => "Niger"),
        array("id" => 6, "name" => "Nigeria"),
        array("id" => 6, "name" => "Rwanda"),
        array("id" => 6, "name" => "Réunion"),
        array("id" => 6, "name" => "Saint Helena"),
        array("id" => 6, "name" => "Senegal"),
        array("id" => 6, "name" => "Seychelles"),
        array("id" => 6, "name" => "Sierra Leone"),
        array("id" => 6, "name" => "Somalia"),
        array("id" => 6, "name" => "South Africa"),
        array("id" => 6, "name" => "Sudan"),
        array("id" => 6, "name" => "Swaziland"),
        array("id" => 6, "name" => "São Tomé and Príncipe"),
        array("id" => 6, "name" => "Tanzania"),
        array("id" => 6, "name" => "Togo"),
        array("id" => 6, "name" => "Tunisia"),
        array("id" => 6, "name" => "Uganda"),
        array("id" => 6, "name" => "Western Sahara"),
        array("id" => 6, "name" => "Zambia"),
        array("id" => 6, "name" => "Zimbabwe")
    ));
}